spring:
  h2:
    console:
      enabled : true # access h2 console through http://localhost:8080/h2-console App needs to be a web app
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties.hibernate.format_sql: true


